#!/usr/bin/env python

from argparse import ArgumentParser
from requests import post

parser = ArgumentParser()
parser.add_argument('-a', '--artifact', default='1')
parser.add_argument('-b', '--backend', default='cuckoo')
parser.add_argument('-r', '--verdict', default='50')
args = parser.parse_args()

if args.verdict in ('', 'none', 'null'):
    value = None
else:
    value = int(args.verdict)

r = post('http://127.0.0.1:9080/artifact/%s' % args.artifact,
         headers={'Content-Type': 'application/json',
                  'Authorization': 'Bearer ' + args.backend},
         json={'verdict_value': value})
r.raise_for_status()
print(r.text)
